export const SocketActions = {
    JOIN: "join",
    JOINED: "user:joined",
    DISCONNECTED: "user:disconnected",
    CODE_CHANGE: "code:change",
    TEXT_CHANGE: "text:change",
    INPUT_CHANGE: "input:change",
    LANGUAGE_CHANGE: "language:change",
    ACTIVITY_CHANGE: "activity:change",
    LEAVED: "user:leaved",
    SEND_MESSAGE: "send:message",
    ROOM_USERS: "room:users",
    SYNC_TEXT: "text:sync",
    SYNC_USER: "user:sync",
    SYNC_CODE: "code:sync",
};
